name: planit
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^3.0.0
  lottie: ^3.3.1
  hooks_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  go_router: ^15.1.3
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.12
  flutter_riverpod: ^2.6.1
  kakao_flutter_sdk: ^1.9.7+3
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  flutter_naver_login: ^2.1.1
  json_annotation: ^4.9.0
  smooth_page_indicator: ^1.2.1
  flutter_hooks: ^0.21.2
  numberpicker: ^2.1.2
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.3.3
  freezed: ^3.0.6
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/mascots/
    - assets/planets/
    - assets/templates/
    - assets/onboarding/
    - assets/.env

  fonts:
    - family: Pretendard
      fonts:
        - asset: fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: fonts/Pretendard-Black.ttf
          weight: 900
    - family: BlackHanSans
      fonts:
        - asset: fonts/BlackHanSans-Regular.ttf
          weight: 400