default_platform(:android)

platform :android do
    desc "Planit"
    lane :distribute do
        # apk 빌드 명령어 실행
        sh("cd .. && fvm flutter build apk --release")

        # 생성된 apk > app distribution 업로드
        release = firebase_app_distribution(
            app: "1:895754219044:android:9706c863a28390e93332b1",
            testers: "kimyohada226@gmail.com, eg4rang2003@gmail.com",
            release_notes: "v1.0.0 찐 배포버전!",

            android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk"
        )

        # 슬랙 알림 전송
        slack(
            message: ":bird: 테스트앱이 올라왔다짹! \n [출시노트] 찐찐찐이야 완전히 찐이야",
            slack_url: "https://hooks.slack.com/services/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"
        )
    end
end
