name: Create Branch
on:
  issues:
    types:
      - opened

jobs:
  create-branch:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: '.github/ISSUE_TEMPLATE/issue-form.yml'

      - name: Log Issue Parser
        run: |
          echo 'Ticket Number: ${{ steps.issue-parser.outputs.__ticket }}'
          echo 'Parsed JSON: ${{ steps.issue-parser.outputs.jsonString }}'

      - name: Create branch with Ticket number
        run: |
          TICKET_NUMBER="${{ steps.issue-parser.outputs.issueparser__ticket_number }}"
          ISSUE_TITLE="${{ steps.issue-parser.outputs.issueparser__branch }}"
          GITHUB_ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          CLEAN_TITLE="$(echo ${ISSUE_TITLE} | sed 's/[^a-zA-Z0-9/_-]/-/g' | sed 's/ /-/g' | sed 's/--*/-/g')"
          
          BRANCH_NAME="${TICKET_NUMBER}/${CLEAN_TITLE}"
          
          git checkout -b "${BRANCH_NAME}"
          git push origin "${BRANCH_NAME}"